### ISSUE TITLE
Breadcrumbs for Eloquent model views

### ISSUE THREAD

**Issue by MartinP7r** [BabDev/laravel-breadcrumbs#1]
Hi there!

First of all thank you for taking over this project!

I was wondering whether the following would be possible:

In a standard Eloquent Model with Controller, I have the following views:

- index
- show
- edit

It seems obvious that the order of breadcrumbs would be `Index / Show / Edit`.  
The `Index`-Breadcrumb should show as the actual model name, and then it makes more sense to display the `Show`-Breadcrumb as the actual `id` of the model.  

Visually that would mean something like 

- `Posts` for `index`
- `Posts / 123` for `show`
- `Posts / 123 / Edit` for `edit`

I was able to implement that. However in terms of UX I'd like to make the structure more concise and put the model id as an independent part of the breadcrumbs for `show` and `edit`. Something like the following

- `Posts` for index (as before)
- `Posts / 123 / Details` for `show`, where `123 / Details` could be the current route (= no hyperlink)
- `Posts / 123 / Edit` for `edit`, where `123` links to `show` (!)

So, the parent for both `show` and `edit` would be `index`, however...

---

I basically just came up with a (kind of hacky) solution while writing this (rubber-ducking for the win!).  
I will just push a `<a href="ROUTE_TO_SHOW">123</a> / Edit` for the `edit` breadcrumb.  

If there's a better solution after all, please let me know.

I'll leave this here in case anybody else comes up with the same problem.

**Comment by MartinP7r** [comment]
Aaaand I just realized that's not working with the default blade. So I set a custom view in the `config/breadcrumbs.php` option and replaced `{{ $breadcrumb->title }}` with `{!! $breadcrumb->title !!}` for now.  
That's doing what I want, however using `{!! !!}` by default is not ideal, so an `insecure` option (maybe an `options` array as a fourth parameter in `$trail->push()` ) might be reasonable if more cases like this arise.

**Comment by mbabker** [comment]
I'd do this off hand:

```php
Breadcrumbs::for('posts.index', static function (BreadcrumbsGenerator $trail): void {
    $trail->push('Posts', route('posts.index'));
});

Breadcrumbs::for('posts.show', static function (BreadcrumbsGenerator $trail, Post $post): void {
    $trail->parent('posts.index');
    $trail->push($post->id);
    $trail->push('Details');
});

Breadcrumbs::for('posts.edit', static function (BreadcrumbsGenerator $trail, Post $post): void {
    $trail->parent('posts.index');
    $trail->push($post->id, route('posts.show', ['post' => $post->id]));
    $trail->push('Edit');
});
```

For the show path, if you don't push a route into a breadcrumb the templates by default treat it as an active segment and it's not shown as a link (example on https://www.babdev.com/open-source/packages/laravel-breadcrumbs/docs/1.x/advanced-usage and https://github.com/BabDev/babdev.com/blob/production/routes/breadcrumbs.php#L42-L53 for generator code).  Then for the edit path it's just pushing a linked segment for the ID then a non-linked segment for the "Edit" text.

**Comment by MartinP7r** [comment]
Wow, that's neat and some much cleaner. Thank you!
